name: A workflow for my Hello World file
on:
 workflow_dispatch:
jobs:
  build:
    name: Hello world action
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Bharti"
      - uses: ./action-b
        with:
          MY_NAME: "Kaushik"
